# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               skyselvlz
tagline:             'site'
description:         'My own website'
disqus_shortname:    skyselvlz

# url:
baseurl:             ''
paginate:            5
paginate_path: "/blog/page:num/"

# About/contact
# author:
#  name:
#  url:
#  email:

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]

github:
  repo: https://github.com/skyselvlz/skyselvlz.github.io
